<main class="about-main">
    <div class="about-container">
        <h1 class="about-title">About Nguyen Thanh Gallery</h1>
        <section class="about-content">
            <div class="about-text">
                <p>Founded in 2000 by artist Nguyen Thanh, <strong class="strong-text-highlight">Nguyen Thanh Gallery</strong> was established with a simple vision: to create a professional platform where contemporary Vietnamese artists could develop their practices over time and present their work within thoughtfully curated exhibitions.</p>
                <p>For more than twenty-five years, the gallery has grown through a commitment to artistic integrity, long-term collaboration, and professional representation. Rather than focusing solely on individual exhibitions, <strong class="strong-text-highlight">Nguyen Thanh Gallery</strong> works closely with its represented artists to support the development of coherent bodies of work, meaningful public engagement, and sustainable artistic careers.</p>
                <p>As Founder, Artist, and Artistic Director, Nguyen Thanh continues to lead the gallery's artistic vision. Drawing on decades of experience as a practicing artist, he oversees the gallery's artistic programme, contributes to exhibition development, and guides the selection of represented artists. His belief in artistic authenticity and continuous creative exploration remains central to the gallery's identity.</p>
                <p>Since 2008, Nguyen Trang has served as Gallery Director, overseeing the gallery's operations, exhibitions, artist relations, collector services, and international partnerships. Working closely with Nguyen Thanh, she has played an important role in expanding the gallery's professional activities, strengthening its relationships with collectors and institutions, and coordinating its participation in international art fairs.</p>
                <p>Today, <strong class="strong-text-highlight">Nguyen Thanh Gallery</strong> represents a carefully selected group of contemporary Vietnamese artists whose practices reflect diverse perspectives within contemporary painting. Through exhibitions, catalogues, publications, and collaborative projects, the gallery seeks to provide meaningful opportunities for artists while encouraging dialogue between Vietnamese contemporary art and the international art community.</p>
                <p>Over the years, <strong class="strong-text-highlight">Nguyen Thanh Gallery</strong> has organized exhibitions throughout Vietnam and participated in international art fairs, introducing its artists to collectors, curators, galleries, and cultural institutions across different countries. These experiences continue to shape the gallery's commitment to professional standards, thoughtful presentation, and long-term artistic development.</p>
                <p>Looking forward, <strong class="strong-text-highlight">Nguyen Thanh Gallery</strong> remains dedicated to supporting artists through sustained representation, carefully developed exhibitions, international collaboration, and ongoing cultural exchange. The gallery believes that lasting artistic value is built through integrity, consistency, and a genuine commitment to the development of both artists and audiences.</p>
            </div>
        </section>
    </div>
</main>
